<?php
include 'vendor/autoload.php';
//include 'Ancestor.php';
//include 'Child1.php';
//include 'Child2.php';
//include 'Child3.php';
//include 'GrandChild1_1.php';
//include 'GrandChild1_2.php';
//include 'GrandChild2_1.php';
//include 'GrandChild2_2.php';
use Core\Ancestor;
use Core\Child1;
use Core\Child2;
use Core\Child3;
use Core\GrandChild1_1;
use Core\GrandChild1_2;
use Core\GrandChild2_1;
use Core\GrandChild2_2;

$a = new Child1();
$a->setOne1(0, 1);
$a->getOne1(0);
echo ($a->getOne1(0)).'<br>';
echo ($a->getArrSum()).'<br>';
echo ($a->getExponent(7, 2)).'<br>';
$b = new Child2();
$b->setOne2(0, 2);
$b->getOne2(0);
echo ($b->getArrSum1()).'<br>';
$c = new Child3();
$c->setOne3(0, 3);
$c->getOne3(0);
echo ($c->getArrSum2()).'<br>';
$d = new GrandChild1_1();
$d->push_int();
$d->sum();
$e = new GrandChild1_2();
$e->push_int1();
$e->sum1();
$j = new GrandChild2_1();
$j->push_int2();
$j->multi();
$f = new GrandChild2_2();
$f->push_int3();
$f->multi1();

